custom dataset loader
QData/TextAttack pull request #324
Opened 2020-11-04 13:19 UTC by ArshdeepSekhon

loads a user specified dataset from local file as text attack dataset using hugging face data loader utils:
1. Adds a CustomDataset class to textattack datasets module
2. Converts a user specified dataset into a text attack dataset using hugging face data loader utils
3. Allows user to specify input and output columns from a local file/ pandas data frame/ dict
4. accordingly changes the augment command line from csv reader to CustomDataset

2020-11-04 15:42 UTC, qiyanjun commented
@ArshdeepSekhon is this a continued PR from 310? If yes, I will close that one. 

@ArshdeepSekhon there are some issues with the flair library dependency, so we fix that in the https://github.com/QData/TextAttack/pull/322

2020-11-04 21:15 UTC, ArshdeepSekhon commented
@qiyanjun This is a different PR , #310 adds an additional command to let the user specify `eval` on an entire dataset instead of sampling a subset.

2020-11-06 02:38 UTC, jinyongyoo requested changes
I didn't know `datasets` offered an easy way to load datasets from file, so this CustomDataset class was cool to see! I made some minor comments about handling some edge cases.

The biggest comment that I have is that after reading the code for this class, I'm still not completely sure how to use it. I think part of it can be resolved with more detailed documentation. But also, I think part of it is that we're abstracting too much away from the users. We are coupling `CustomDataset` so tightly with Huggingface's `dataset` package. Part of me feels like it would easier for users if we can just require users to create the appropriate `datasets.Dataset` object and pass it directly instead of requiring them to provide the arguments that are eventually used to build the `datasets.Dataset` object. After all, Huggingface has better documentation and examples for guiding users how to build the dataset. Then, we can simply skip most of the complicated logic in `__init__` and just focus on packing the examples as `OrderedDict` for TextAttack.

2020-11-06 02:38 UTC, jinyongyoo commented on textattack/datasets/custom_dataset.py
> +    - name(Union[str, dict, pd.DataFrame]): the user specified dataset file names, dicts or pandas dataframe
Don't you think `name` argument would be too confusing? Maybe `file_name_or_data`?

2020-11-07 04:21 UTC, qiyanjun commented
@ArshdeepSekhon It is a good idea to sync your copy of the code with the master repository regularly. This way you can quickly account for changes:

$ git remote add upstream https://github.com/QData/TextAttack
$ git fetch upstream
$ git rebase upstream/master

2020-11-25 00:08 UTC, qiyanjun commented
@ArshdeepSekhon please run

"black textattack" to correct all formatting issues first.
"isort textattack" to correct all import issues then.
"make test" then

2020-12-05 02:09 UTC, qiyanjun commented
@ArshdeepSekhon let me fix the build doc

2020-12-05 04:47 UTC, qiyanjun commented
@ArshdeepSekhon @jinyongyoo I thought datasets/dataset.py should be @abstractclass with some must @abstractmethod ..

```
import abc

class AbstractClass(metaclass=abc.ABCMeta):

    @abc.abstractmethod
    def abstractMethod(self):
        return
```

2020-12-05 04:55 UTC, qiyanjun commented
@ArshdeepSekhon @jinyongyoo I recommend we triangle this PR for now.. Agreed?

2020-12-07 01:25 UTC, closed without merging