Extra quality metrics
QData/TextAttack pull request #695
Opened 2022-10-03 13:52 UTC by gmurro

Add extra quality metrics: BERTScore, Sentence BERT and Meteor.

A better default model has been setted for BERTScore (as described in this [sheet](https://docs.google.com/spreadsheets/d/1RKOVpselB98Nnh_EOC4A2BYn8_201tmPODpNWu4w7xI/edit#gid=0))
How to use them?

```
attack_results = attacker.attack_dataset()

sbert_stats = SBERTMetric().calculate(attack_results)
bert_score_stats = BERTScoreMetric().calculate(attack_results)
meteor_stats = MeteorMetric().calculate(attack_results)
```

2022-10-27 17:42 UTC, jxmorris12 requested changes
Code looks great, just one question about restoring defaults for BertScore. As long as you resolve that and tests pass, we should be good to merge.

2022-12-15 10:40 UTC, gmurro commented on textattack/constraints/semantics/bert_score.py
> +        model_name="microsoft/deberta-large-mnli",
Yeah, you are right! We can leave `bert-base-uncased` as default

2022-12-15 13:13 UTC, jxmorris12 commented on textattack/constraints/semantics/bert_score.py
> +        model_name="microsoft/deberta-large-mnli",
can you fix and update the pr?

2022-12-15 19:25 UTC, gmurro commented on textattack/constraints/semantics/bert_score.py
> +        model_name="microsoft/deberta-large-mnli",
I just did, is there something else that I should do to merge the code?

2022-12-15 22:49 UTC, jxmorris12 approved these changes

2022-12-15 22:49 UTC, merged